# Generated by Django 2.1.3 on 2018-12-05 02:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=250)),
                ('publish_date', models.DateTimeField(verbose_name='publish_date')),
                ('console', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GameReview',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField()),
                ('publish_date', models.DateTimeField(verbose_name='publish_date')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Game')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('creation_date', models.DateTimeField(verbose_name='creation date')),
            ],
        ),
        migrations.AddField(
            model_name='gamereview',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.User'),
        ),
    ]
